name: "UpCloud CLI for Github Actions"
description: "Installs and configures the UpCloud command-line tool (upctl) for managing UpCloud infrastructure in GitHub Actions."
author: "UpCloud"
branding:
  icon: "cloud"
  color: "purple"
inputs:
  version:
    description: "UpCloud CLI version to install"
    default: "latest"
  username:
    description: "UpCloud API Username"
  password:
    description: "UpCloud API Password"
  token:
    description: "UpCloud API Token. If set, username and password are ignored."
  verify-attestation:
    description: "Whether to verify the artifact attestation of the downloaded upctl during install."
    default: true
runs:
  using: "node20"
  main: "dist/index.js"
