name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Lint, build, and use
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Build action
        run: npm run package

      - name: Check dist directory is up-to-date
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after build. Run 'npm run package' command and commit."; exit 1)

      - name: Test action execution
        uses: ./
        with:
          username: ${{ secrets.UPCLOUD_USERNAME }}
          password: ${{ secrets.UPCLOUD_PASSWORD }}
          version: 'latest'